version: '2.3'
services:
  couchdb:
    container_name: couchdb
    image: couchdb
    environment:
      COUCHDB_DEV_INIT: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: test-cookie
    ports:
    - "5984:5984"
    - "5986:5986"
    volumes:
      - type: bind
        source: ./data
        target: /opt/couchdb/data